version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - "8081:80"         # HTTP traffic
      - "8083:8083"      # Traefik dashboard
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/rules.yml:/etc/traefik/rules.yml:ro"
    networks:
      - podman
    restart: unless-stopped
    depends_on:
      - "projekt1"
      - "projekt2"

  projekt1:
    build: ./projekt1
    networks:
      - podman
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projekt1.rule=Host(`localhost`) && PathPrefix(`/projekt1`)"
      - "traefik.http.routers.projekt1.entrypoints=web"
      - "traefik.http.services.projekt1.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/projekt1"
      - "traefik.http.routers.projekt1.middlewares=strip-prefix@docker"
    restart: unless-stopped

  projekt2:
    build: ./projekt2
    networks:
      - podman
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projekt2.rule=Host(`localhost`) && PathPrefix(`/projekt2`)"
    restart: unless-stopped

networks:
  podman:
    name: podman
    external: false
