# rules.yml
http:
  routers:
    # Dashboard
    dashboard:
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      service: api@internal
      entryPoints:
        - "dashboard"
      middlewares:
        - "dashboard-stripprefix"

    # Project 1
    projekt1:
      rule: "PathPrefix(`/projekt1`)"
      service: projekt1
      entryPoints:
        - "web"
      middlewares:
        - "projekt1-stripprefix"

    # Project 2
    projekt2:
      rule: "PathPrefix(`/projekt2`)"
      service: projekt2
      entryPoints:
        - "web"
      middlewares:
        - "projekt2-stripprefix"

  services:
    # Project 1 service
    projekt1:
      loadBalancer:
        servers:
          - url: "http://python-podman-traefik_projekt1_1:5000"

    # Project 2 service
    projekt2:
      loadBalancer:
        servers:
          - url: "http://python-podman-traefik_projekt2_1:5000"

  middlewares:
    # Strip /projekt1 prefix
    projekt1-stripprefix:
      stripPrefix:
        prefixes:
          - "/projekt1"

    # Strip /projekt2 prefix
    projekt2-stripprefix:
      stripPrefix:
        prefixes:
          - "/projekt2"

    # Strip /dashboard prefix
    dashboard-stripprefix:
      stripPrefix:
        prefixes:
          - "/dashboard"
        forceSlash: true
