# traefik.yml
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8083"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only expose containers with traefik.enable=true
    network: podman          # Match your Podman network name
    useBindPortIP: false     # Important for Podman compatibility
    watch: true

serversTransport:
  insecureSkipVerify: true

log:
  level: DEBUG
  format: common
