# Minimalna konfiguracja Traefik pod Podman Compose
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8083"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: podman
    useBindPortIP: false
    watch: true

log:
  level: DEBUG
  format: common
