---
- name: Test Podman Traefik Setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check if Traefik dashboard is accessible
      uri:
        url: http://localhost:8083/dashboard/
        method: GET
        status_code: 200
        timeout: 5
      register: traefik_dashboard
      ignore_errors: yes

    - name: Check Traefik dashboard headers
      uri:
        url: http://localhost:8083/dashboard/
        method: GET
        status_code: 200
        return_content: no
      register: traefik_headers

    - name: Assert Traefik Server header
      assert:
        that:
          - traefik_headers.response_headers is defined
          - traefik_headers.response_headers['server'] is defined
          - "'traefik' in traefik_headers.response_headers['server'] | lower"

    - name: Check Projekt1 service
      uri:
        url: http://localhost:8081/projekt1
        method: GET
        status_code: 200
        return_content: yes
        timeout: 5
      register: projekt1_check
      until: projekt1_check.status == 200
      retries: 3
      delay: 2

    - name: Check Projekt2 service
      uri:
        url: http://localhost:8081/projekt2
        method: GET
        status_code: 200
        return_content: yes
        timeout: 5
      register: projekt2_check
      until: projekt2_check.status == 200
      retries: 3
      delay: 2

    - name: Show test results
      debug:
        msg:
          - "Traefik Dashboard: {{ 'Accessible' if traefik_dashboard.status == 200 else 'Not Accessible' }}"
          - "Projekt1 Status: {{ projekt1_check.status }} - Content: {{ projekt1_check.content | b64decode | regex_search('>([^<]+)<') | default('No content') }}"
          - "Projekt2 Status: {{ projekt2_check.status }} - Content: {{ projekt2_check.content | b64decode | regex_search('>([^<]+)<') | default('No content') }}"
